### ISSUE TITLE
set password Openvpn

### ISSUE THREAD

**Issue by gabrielwpulido** [NerdOfLinux/OpenVPN-Installer#1]
Hi again man, please, how could I script ask me for setting password to my openvpn new users? Thanks

**Comment by NerdOfLinux** [comment]
The script currently doesn't support setting up password-based authentication. However, once OpenVPN is installed, you should be able to follow [this answer](https://serverfault.com/a/837252) to configure it manually.

**Comment by gabrielwpulido** [comment]
Thank U man
